generate-new-amm-fixture: build-amm-program-fixture
    cp ../../mercurial-dynamic-amm/target/deploy/amm.so ./fixtures/amm.so

build-amm-program-fixture:
    cd ../../mercurial-dynamic-amm/ && anchor build